

[ERROR] 2018-09-26 16:07:20,562 method:org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:331)
Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xsl.sso.service.JWTService': Cannot resolve reference to bean 'jWTServiceImpl' while setting bean property 'ref'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'jWTServiceImpl' is defined
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1469)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:762)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'jWTServiceImpl' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:694)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1157)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:280)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 24 more


[ERROR] 2018-09-26 16:08:55,865 method:org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:331)
Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xsl.sso.service.JWTService': Cannot resolve reference to bean 'jWTServiceImpl' while setting bean property 'ref'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'jWTServiceImpl' is defined
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1469)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:762)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'jWTServiceImpl' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:694)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1157)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:280)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 24 more


[ERROR] 2018-09-26 16:09:59,804 method:org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:331)
Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xsl.sso.service.JWTService': Cannot resolve reference to bean 'jwtServiceImpl' while setting bean property 'ref'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'jwtServiceImpl' is defined
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1469)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:762)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'jwtServiceImpl' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:694)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1157)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:280)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 24 more


[ERROR] 2018-10-02 10:08:10,042 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:08:34,323 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:08:52,708 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:10:55,023 method:com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:87)
 [DUBBO] Got unchecked and undeclared exception which called by 192.168.56.1. service: xsl.sso.service.LoginService, method: getLoginResult, exception: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset, dubbo version: 2.5.3, current host: 127.0.0.1
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:201)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:132)
	at redis.clients.jedis.Protocol.read(Protocol.java:196)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:288)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:187)
	at redis.clients.jedis.Jedis.set(Jedis.java:66)
	at sso.utils.JedisClientPool.set(JedisClientPool.java:23)
	at xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:72)
	at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:195)
	... 36 more


[ERROR] 2018-10-02 10:11:05,366 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:32:06,223 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:32:30,424 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:38:34,016 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:38:40,692 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:38:44,851 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:40:44,777 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:40:50,253 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:40:53,687 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 10:50:05,502 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 11:19:57,942 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 11:24:21,877 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 11:26:58,492 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 11:28:32,910 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 11:29:07,729 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 11:30:23,484 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 11:31:16,893 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 11:34:13,454 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 11:39:07,056 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:05:15,460 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:07:04,523 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:13:55,349 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:15:51,602 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:16:00,901 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:17:30,734 method:com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:87)
 [DUBBO] Got unchecked and undeclared exception which called by 192.168.56.1. service: xsl.sso.service.LoginService, method: getLoginResult, exception: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool, dubbo version: 2.5.3, current host: 127.0.0.1
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:50)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:86)
	at sso.utils.JedisClientPool.set(JedisClientPool.java:22)
	at xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:72)
	at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused: connect
	at redis.clients.jedis.Connection.connect(Connection.java:155)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:83)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1643)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:85)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:861)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:48)
	... 31 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:149)
	... 38 more


[ERROR] 2018-10-02 12:20:19,281 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:23:35,525 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:24:07,804 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:40:20,469 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:44:21,013 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:44:21,033 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 12:47:52,661 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 13:37:20,558 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 13:46:48,334 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 13:56:20,162 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 14:00:02,670 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 14:04:21,896 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 14:04:59,885 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 14:07:55,601 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 14:11:11,829 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 14:11:50,350 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 14:19:43,281 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 14:21:23,525 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 14:24:25,835 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 14:34:29,602 method:com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:87)
 [DUBBO] Got unchecked and undeclared exception which called by 192.168.56.1. service: xsl.sso.service.LoginService, method: getLoginResult, exception: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool, dubbo version: 2.5.3, current host: 127.0.0.1
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:50)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:86)
	at sso.utils.JedisClientPool.set(JedisClientPool.java:22)
	at xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:72)
	at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused: connect
	at redis.clients.jedis.Connection.connect(Connection.java:155)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:83)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1643)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:85)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:861)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:48)
	... 31 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:149)
	... 38 more


[ERROR] 2018-10-02 14:50:55,800 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 15:02:27,360 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 15:03:58,942 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 15:06:09,859 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功


[ERROR] 2018-10-02 15:16:02,134 method:xsl.sso.service.impl.LoginServiceImpl.getLoginResult(LoginServiceImpl.java:75)
管理员：测试管理员登录成功
